// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: entpb/entpb.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwoWord_Enums int32

const (
	TwoWord_OPTION1 TwoWord_Enums = 0
	TwoWord_OPTION2 TwoWord_Enums = 1
)

// Enum value maps for TwoWord_Enums.
var (
	TwoWord_Enums_name = map[int32]string{
		0: "OPTION1",
		1: "OPTION2",
	}
	TwoWord_Enums_value = map[string]int32{
		"OPTION1": 0,
		"OPTION2": 1,
	}
)

func (x TwoWord_Enums) Enum() *TwoWord_Enums {
	p := new(TwoWord_Enums)
	*p = x
	return p
}

func (x TwoWord_Enums) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TwoWord_Enums) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[0].Descriptor()
}

func (TwoWord_Enums) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[0]
}

func (x TwoWord_Enums) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TwoWord_Enums.Descriptor instead.
func (TwoWord_Enums) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{0, 0}
}

type GetTwoWordRequest_View int32

const (
	GetTwoWordRequest_VIEW_UNSPECIFIED GetTwoWordRequest_View = 0
	GetTwoWordRequest_BASIC            GetTwoWordRequest_View = 1
	GetTwoWordRequest_WITH_EDGE_IDS    GetTwoWordRequest_View = 2
)

// Enum value maps for GetTwoWordRequest_View.
var (
	GetTwoWordRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetTwoWordRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetTwoWordRequest_View) Enum() *GetTwoWordRequest_View {
	p := new(GetTwoWordRequest_View)
	*p = x
	return p
}

func (x GetTwoWordRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTwoWordRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[1].Descriptor()
}

func (GetTwoWordRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[1]
}

func (x GetTwoWordRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTwoWordRequest_View.Descriptor instead.
func (GetTwoWordRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2, 0}
}

type TwoWord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enums TwoWord_Enums `protobuf:"varint,2,opt,name=enums,proto3,enum=entpb.TwoWord_Enums" json:"enums,omitempty"`
}

func (x *TwoWord) Reset() {
	*x = TwoWord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entpb_entpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoWord) ProtoMessage() {}

func (x *TwoWord) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoWord.ProtoReflect.Descriptor instead.
func (*TwoWord) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *TwoWord) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TwoWord) GetEnums() TwoWord_Enums {
	if x != nil {
		return x.Enums
	}
	return TwoWord_OPTION1
}

type CreateTwoWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TwoWord *TwoWord `protobuf:"bytes,1,opt,name=two_word,json=twoWord,proto3" json:"two_word,omitempty"`
}

func (x *CreateTwoWordRequest) Reset() {
	*x = CreateTwoWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entpb_entpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTwoWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTwoWordRequest) ProtoMessage() {}

func (x *CreateTwoWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTwoWordRequest.ProtoReflect.Descriptor instead.
func (*CreateTwoWordRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTwoWordRequest) GetTwoWord() *TwoWord {
	if x != nil {
		return x.TwoWord
	}
	return nil
}

type GetTwoWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	View GetTwoWordRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetTwoWordRequest_View" json:"view,omitempty"`
}

func (x *GetTwoWordRequest) Reset() {
	*x = GetTwoWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entpb_entpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTwoWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTwoWordRequest) ProtoMessage() {}

func (x *GetTwoWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTwoWordRequest.ProtoReflect.Descriptor instead.
func (*GetTwoWordRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetTwoWordRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTwoWordRequest) GetView() GetTwoWordRequest_View {
	if x != nil {
		return x.View
	}
	return GetTwoWordRequest_VIEW_UNSPECIFIED
}

type UpdateTwoWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TwoWord *TwoWord `protobuf:"bytes,1,opt,name=two_word,json=twoWord,proto3" json:"two_word,omitempty"`
}

func (x *UpdateTwoWordRequest) Reset() {
	*x = UpdateTwoWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entpb_entpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTwoWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTwoWordRequest) ProtoMessage() {}

func (x *UpdateTwoWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTwoWordRequest.ProtoReflect.Descriptor instead.
func (*UpdateTwoWordRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTwoWordRequest) GetTwoWord() *TwoWord {
	if x != nil {
		return x.TwoWord
	}
	return nil
}

type DeleteTwoWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTwoWordRequest) Reset() {
	*x = DeleteTwoWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entpb_entpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTwoWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTwoWordRequest) ProtoMessage() {}

func (x *DeleteTwoWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTwoWordRequest.ProtoReflect.Descriptor instead.
func (*DeleteTwoWordRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTwoWordRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_entpb_entpb_proto protoreflect.FileDescriptor

var file_entpb_entpb_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x07, 0x54, 0x77, 0x6f, 0x57, 0x6f,
	0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72,
	0x64, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x52, 0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x22, 0x21,
	0x0a, 0x05, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x50, 0x54, 0x49, 0x4f,
	0x4e, 0x31, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x32, 0x10,
	0x01, 0x22, 0x41, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x77, 0x6f, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x74, 0x77, 0x6f,
	0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x6e,
	0x74, 0x70, 0x62, 0x2e, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x74, 0x77, 0x6f,
	0x57, 0x6f, 0x72, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x77, 0x6f, 0x57,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x76, 0x69,
	0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x22, 0x3a, 0x0a,
	0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x10, 0x56, 0x49, 0x45, 0x57, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42,
	0x41, 0x53, 0x49, 0x43, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x57, 0x49, 0x54, 0x48, 0x5f, 0x45,
	0x44, 0x47, 0x45, 0x5f, 0x49, 0x44, 0x53, 0x10, 0x02, 0x22, 0x41, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x29, 0x0a, 0x08, 0x74, 0x77, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x54, 0x77, 0x6f, 0x57,
	0x6f, 0x72, 0x64, 0x52, 0x07, 0x74, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x22, 0x26, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x32, 0xee, 0x01, 0x0a, 0x0e, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1b, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x2f,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x12,
	0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x65, 0x6e, 0x74, 0x70,
	0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x54,
	0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x3d, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x1b, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x77, 0x6f, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x1e, 0x5a, 0x1c, 0x65, 0x6e, 0x74, 0x67, 0x6f, 0x2e, 0x69,
	0x6f, 0x2f, 0x62, 0x75, 0x67, 0x2f, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x6e, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entpb_entpb_proto_rawDescOnce sync.Once
	file_entpb_entpb_proto_rawDescData = file_entpb_entpb_proto_rawDesc
)

func file_entpb_entpb_proto_rawDescGZIP() []byte {
	file_entpb_entpb_proto_rawDescOnce.Do(func() {
		file_entpb_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_entpb_entpb_proto_rawDescData)
	})
	return file_entpb_entpb_proto_rawDescData
}

var file_entpb_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_entpb_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_entpb_entpb_proto_goTypes = []interface{}{
	(TwoWord_Enums)(0),           // 0: entpb.TwoWord.Enums
	(GetTwoWordRequest_View)(0),  // 1: entpb.GetTwoWordRequest.View
	(*TwoWord)(nil),              // 2: entpb.TwoWord
	(*CreateTwoWordRequest)(nil), // 3: entpb.CreateTwoWordRequest
	(*GetTwoWordRequest)(nil),    // 4: entpb.GetTwoWordRequest
	(*UpdateTwoWordRequest)(nil), // 5: entpb.UpdateTwoWordRequest
	(*DeleteTwoWordRequest)(nil), // 6: entpb.DeleteTwoWordRequest
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_entpb_entpb_proto_depIdxs = []int32{
	0, // 0: entpb.TwoWord.enums:type_name -> entpb.TwoWord.Enums
	2, // 1: entpb.CreateTwoWordRequest.two_word:type_name -> entpb.TwoWord
	1, // 2: entpb.GetTwoWordRequest.view:type_name -> entpb.GetTwoWordRequest.View
	2, // 3: entpb.UpdateTwoWordRequest.two_word:type_name -> entpb.TwoWord
	3, // 4: entpb.TwoWordService.Create:input_type -> entpb.CreateTwoWordRequest
	4, // 5: entpb.TwoWordService.Get:input_type -> entpb.GetTwoWordRequest
	5, // 6: entpb.TwoWordService.Update:input_type -> entpb.UpdateTwoWordRequest
	6, // 7: entpb.TwoWordService.Delete:input_type -> entpb.DeleteTwoWordRequest
	2, // 8: entpb.TwoWordService.Create:output_type -> entpb.TwoWord
	2, // 9: entpb.TwoWordService.Get:output_type -> entpb.TwoWord
	2, // 10: entpb.TwoWordService.Update:output_type -> entpb.TwoWord
	7, // 11: entpb.TwoWordService.Delete:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_entpb_entpb_proto_init() }
func file_entpb_entpb_proto_init() {
	if File_entpb_entpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entpb_entpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwoWord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entpb_entpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTwoWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entpb_entpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTwoWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entpb_entpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTwoWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entpb_entpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTwoWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entpb_entpb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entpb_entpb_proto_goTypes,
		DependencyIndexes: file_entpb_entpb_proto_depIdxs,
		EnumInfos:         file_entpb_entpb_proto_enumTypes,
		MessageInfos:      file_entpb_entpb_proto_msgTypes,
	}.Build()
	File_entpb_entpb_proto = out.File
	file_entpb_entpb_proto_rawDesc = nil
	file_entpb_entpb_proto_goTypes = nil
	file_entpb_entpb_proto_depIdxs = nil
}
