// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ent/twoword"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TwoWordQuery is the builder for querying TwoWord entities.
type TwoWordQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TwoWord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TwoWordQuery builder.
func (twq *TwoWordQuery) Where(ps ...predicate.TwoWord) *TwoWordQuery {
	twq.predicates = append(twq.predicates, ps...)
	return twq
}

// Limit adds a limit step to the query.
func (twq *TwoWordQuery) Limit(limit int) *TwoWordQuery {
	twq.limit = &limit
	return twq
}

// Offset adds an offset step to the query.
func (twq *TwoWordQuery) Offset(offset int) *TwoWordQuery {
	twq.offset = &offset
	return twq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (twq *TwoWordQuery) Unique(unique bool) *TwoWordQuery {
	twq.unique = &unique
	return twq
}

// Order adds an order step to the query.
func (twq *TwoWordQuery) Order(o ...OrderFunc) *TwoWordQuery {
	twq.order = append(twq.order, o...)
	return twq
}

// First returns the first TwoWord entity from the query.
// Returns a *NotFoundError when no TwoWord was found.
func (twq *TwoWordQuery) First(ctx context.Context) (*TwoWord, error) {
	nodes, err := twq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{twoword.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (twq *TwoWordQuery) FirstX(ctx context.Context) *TwoWord {
	node, err := twq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TwoWord ID from the query.
// Returns a *NotFoundError when no TwoWord ID was found.
func (twq *TwoWordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = twq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{twoword.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (twq *TwoWordQuery) FirstIDX(ctx context.Context) int {
	id, err := twq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TwoWord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TwoWord entity is not found.
// Returns a *NotFoundError when no TwoWord entities are found.
func (twq *TwoWordQuery) Only(ctx context.Context) (*TwoWord, error) {
	nodes, err := twq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{twoword.Label}
	default:
		return nil, &NotSingularError{twoword.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (twq *TwoWordQuery) OnlyX(ctx context.Context) *TwoWord {
	node, err := twq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TwoWord ID in the query.
// Returns a *NotSingularError when exactly one TwoWord ID is not found.
// Returns a *NotFoundError when no entities are found.
func (twq *TwoWordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = twq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = &NotSingularError{twoword.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (twq *TwoWordQuery) OnlyIDX(ctx context.Context) int {
	id, err := twq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TwoWords.
func (twq *TwoWordQuery) All(ctx context.Context) ([]*TwoWord, error) {
	if err := twq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return twq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (twq *TwoWordQuery) AllX(ctx context.Context) []*TwoWord {
	nodes, err := twq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TwoWord IDs.
func (twq *TwoWordQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := twq.Select(twoword.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (twq *TwoWordQuery) IDsX(ctx context.Context) []int {
	ids, err := twq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (twq *TwoWordQuery) Count(ctx context.Context) (int, error) {
	if err := twq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return twq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (twq *TwoWordQuery) CountX(ctx context.Context) int {
	count, err := twq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (twq *TwoWordQuery) Exist(ctx context.Context) (bool, error) {
	if err := twq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return twq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (twq *TwoWordQuery) ExistX(ctx context.Context) bool {
	exist, err := twq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TwoWordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (twq *TwoWordQuery) Clone() *TwoWordQuery {
	if twq == nil {
		return nil
	}
	return &TwoWordQuery{
		config:     twq.config,
		limit:      twq.limit,
		offset:     twq.offset,
		order:      append([]OrderFunc{}, twq.order...),
		predicates: append([]predicate.TwoWord{}, twq.predicates...),
		// clone intermediate query.
		sql:  twq.sql.Clone(),
		path: twq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Enums twoword.Enums `json:"enums,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TwoWord.Query().
//		GroupBy(twoword.FieldEnums).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (twq *TwoWordQuery) GroupBy(field string, fields ...string) *TwoWordGroupBy {
	group := &TwoWordGroupBy{config: twq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := twq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return twq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Enums twoword.Enums `json:"enums,omitempty"`
//	}
//
//	client.TwoWord.Query().
//		Select(twoword.FieldEnums).
//		Scan(ctx, &v)
//
func (twq *TwoWordQuery) Select(fields ...string) *TwoWordSelect {
	twq.fields = append(twq.fields, fields...)
	return &TwoWordSelect{TwoWordQuery: twq}
}

func (twq *TwoWordQuery) prepareQuery(ctx context.Context) error {
	for _, f := range twq.fields {
		if !twoword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if twq.path != nil {
		prev, err := twq.path(ctx)
		if err != nil {
			return err
		}
		twq.sql = prev
	}
	return nil
}

func (twq *TwoWordQuery) sqlAll(ctx context.Context) ([]*TwoWord, error) {
	var (
		nodes = []*TwoWord{}
		_spec = twq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TwoWord{config: twq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, twq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (twq *TwoWordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := twq.querySpec()
	_spec.Node.Columns = twq.fields
	if len(twq.fields) > 0 {
		_spec.Unique = twq.unique != nil && *twq.unique
	}
	return sqlgraph.CountNodes(ctx, twq.driver, _spec)
}

func (twq *TwoWordQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := twq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (twq *TwoWordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   twoword.Table,
			Columns: twoword.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: twoword.FieldID,
			},
		},
		From:   twq.sql,
		Unique: true,
	}
	if unique := twq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := twq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, twoword.FieldID)
		for i := range fields {
			if fields[i] != twoword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := twq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := twq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := twq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := twq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (twq *TwoWordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(twq.driver.Dialect())
	t1 := builder.Table(twoword.Table)
	columns := twq.fields
	if len(columns) == 0 {
		columns = twoword.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if twq.sql != nil {
		selector = twq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if twq.unique != nil && *twq.unique {
		selector.Distinct()
	}
	for _, p := range twq.predicates {
		p(selector)
	}
	for _, p := range twq.order {
		p(selector)
	}
	if offset := twq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := twq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TwoWordGroupBy is the group-by builder for TwoWord entities.
type TwoWordGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (twgb *TwoWordGroupBy) Aggregate(fns ...AggregateFunc) *TwoWordGroupBy {
	twgb.fns = append(twgb.fns, fns...)
	return twgb
}

// Scan applies the group-by query and scans the result into the given value.
func (twgb *TwoWordGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := twgb.path(ctx)
	if err != nil {
		return err
	}
	twgb.sql = query
	return twgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (twgb *TwoWordGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := twgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(twgb.fields) > 1 {
		return nil, errors.New("ent: TwoWordGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := twgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (twgb *TwoWordGroupBy) StringsX(ctx context.Context) []string {
	v, err := twgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = twgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (twgb *TwoWordGroupBy) StringX(ctx context.Context) string {
	v, err := twgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(twgb.fields) > 1 {
		return nil, errors.New("ent: TwoWordGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := twgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (twgb *TwoWordGroupBy) IntsX(ctx context.Context) []int {
	v, err := twgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = twgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (twgb *TwoWordGroupBy) IntX(ctx context.Context) int {
	v, err := twgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(twgb.fields) > 1 {
		return nil, errors.New("ent: TwoWordGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := twgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (twgb *TwoWordGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := twgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = twgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (twgb *TwoWordGroupBy) Float64X(ctx context.Context) float64 {
	v, err := twgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(twgb.fields) > 1 {
		return nil, errors.New("ent: TwoWordGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := twgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (twgb *TwoWordGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := twgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (twgb *TwoWordGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = twgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (twgb *TwoWordGroupBy) BoolX(ctx context.Context) bool {
	v, err := twgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (twgb *TwoWordGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range twgb.fields {
		if !twoword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := twgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := twgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (twgb *TwoWordGroupBy) sqlQuery() *sql.Selector {
	selector := twgb.sql.Select()
	aggregation := make([]string, 0, len(twgb.fns))
	for _, fn := range twgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(twgb.fields)+len(twgb.fns))
		for _, f := range twgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(twgb.fields...)...)
}

// TwoWordSelect is the builder for selecting fields of TwoWord entities.
type TwoWordSelect struct {
	*TwoWordQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tws *TwoWordSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tws.prepareQuery(ctx); err != nil {
		return err
	}
	tws.sql = tws.TwoWordQuery.sqlQuery(ctx)
	return tws.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tws *TwoWordSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tws.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tws.fields) > 1 {
		return nil, errors.New("ent: TwoWordSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tws.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tws *TwoWordSelect) StringsX(ctx context.Context) []string {
	v, err := tws.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tws.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tws *TwoWordSelect) StringX(ctx context.Context) string {
	v, err := tws.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tws.fields) > 1 {
		return nil, errors.New("ent: TwoWordSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tws.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tws *TwoWordSelect) IntsX(ctx context.Context) []int {
	v, err := tws.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tws.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tws *TwoWordSelect) IntX(ctx context.Context) int {
	v, err := tws.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tws.fields) > 1 {
		return nil, errors.New("ent: TwoWordSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tws.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tws *TwoWordSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tws.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tws.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tws *TwoWordSelect) Float64X(ctx context.Context) float64 {
	v, err := tws.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tws.fields) > 1 {
		return nil, errors.New("ent: TwoWordSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tws.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tws *TwoWordSelect) BoolsX(ctx context.Context) []bool {
	v, err := tws.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tws *TwoWordSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tws.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{twoword.Label}
	default:
		err = fmt.Errorf("ent: TwoWordSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tws *TwoWordSelect) BoolX(ctx context.Context) bool {
	v, err := tws.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tws *TwoWordSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tws.sql.Query()
	if err := tws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
